


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pgsodium";






COMMENT ON SCHEMA "public" IS '@graphql({"inflect_names": true})';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."hours_type" AS ENUM (
    'office',
    'grading'
);


ALTER TYPE "public"."hours_type" OWNER TO "postgres";


COMMENT ON TYPE "public"."hours_type" IS 'Different types hours (e.g. office and grading)';



CREATE TYPE "public"."syllabus_category" AS ENUM (
    'essential',
    'policy',
    'university',
    'header'
);


ALTER TYPE "public"."syllabus_category" OWNER TO "postgres";


COMMENT ON TYPE "public"."syllabus_category" IS 'Categories of syllabus entries';



CREATE TYPE "public"."term" AS ENUM (
    'unused',
    'winter',
    'spring',
    'summer',
    'fall'
);


ALTER TYPE "public"."term" OWNER TO "postgres";


COMMENT ON TYPE "public"."term" IS 'Academic term';


SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."course" (
    "id" "text" NOT NULL,
    "number" "text" NOT NULL,
    "title" "text" NOT NULL,
    "terms" "public"."term"[],
    "description" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."course" OWNER TO "postgres";


COMMENT ON TABLE "public"."course" IS 'Courses taught';



CREATE TABLE IF NOT EXISTS "public"."course_term" (
    "id" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "course_id" "text" NOT NULL,
    "term" "public"."term" NOT NULL,
    "year" smallint NOT NULL
);


ALTER TABLE "public"."course_term" OWNER TO "postgres";


COMMENT ON TABLE "public"."course_term" IS 'Table of the terms/years in which each course was offered';



CREATE TABLE IF NOT EXISTS "public"."hours" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "day" "text" NOT NULL,
    "start" time without time zone NOT NULL,
    "end" time without time zone NOT NULL,
    "location" "text" NOT NULL,
    "videoconference_link" "text",
    "extra_info" "text",
    "type" "public"."hours_type" DEFAULT 'office'::"public"."hours_type" NOT NULL,
    "person_id" bigint NOT NULL
);


ALTER TABLE "public"."hours" OWNER TO "postgres";


COMMENT ON TABLE "public"."hours" IS 'Office and grading hours';



ALTER TABLE "public"."hours" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."hours_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."person" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "email" "text" NOT NULL
);


ALTER TABLE "public"."person" OWNER TO "postgres";


COMMENT ON TABLE "public"."person" IS 'People, i.e. me and TAs';



ALTER TABLE "public"."person" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."person_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."course"
    ADD CONSTRAINT "course_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."course_term"
    ADD CONSTRAINT "course_term_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."hours"
    ADD CONSTRAINT "hours_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."person"
    ADD CONSTRAINT "person_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."course_term"
    ADD CONSTRAINT "course_term_course_id_fkey" FOREIGN KEY ("course_id") REFERENCES "public"."course"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."hours"
    ADD CONSTRAINT "hours_person_id_fkey" FOREIGN KEY ("person_id") REFERENCES "public"."person"("id") ON UPDATE CASCADE ON DELETE CASCADE;



CREATE POLICY "Enable read access for all users" ON "public"."course" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."course_term" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."hours" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."person" FOR SELECT USING (true);



ALTER TABLE "public"."course" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."course_term" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."hours" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."person" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";




















































































































































































GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."course" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."course" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."course" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."course_term" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."course_term" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."course_term" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."hours" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."hours" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."hours" TO "service_role";



GRANT ALL ON SEQUENCE "public"."hours_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."hours_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."hours_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."person" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."person" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."person" TO "service_role";



GRANT ALL ON SEQUENCE "public"."person_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."person_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."person_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO "service_role";































drop extension if exists "pg_net";


